input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [message] =~ /^\s*$/ {
    drop { }
  }

  mutate {
    add_field => {
      "source" => "logstash"
      "tenant_id" => "%{[@metadata][tenant_id]}"
    }
  }

  date {
    match => [ "timestamp", "ISO8601", "UNIX_MS" ]
    target => "@timestamp"
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:29092"
    topic_id => "raw-logs"
    codec => json
    compression_type => "lz4"
    acks => "all"
  }
}
